package view;

public class Constants {

	public static final String ERROR_DIALOG_TITLE = "Erro";
	public static final String INFO_DIALOG_TITLE = "Sucesso"; 
	public static final String CREATE_CATEGORY_ERROR = "Erro ao criar a categoria";
	public static final String CREATE_CATEGORY_RECOVERY = "Corrija o nome da categoria e tente de novo";
	public static final String CREATE_CATEGORY_SUCCESS = "Categoria criada com sucesso";
	public static final String CREATE_CATEGORY_INVALID_CATEGORY = "Preencha o nome da categoria";
	public static final String LOGIN_INVALID_USERNAME = "Preencha o nome do utilizador";
	public static final String LOGIN_INVALID_PASSWORD = "Preencha a palavra-passe";
	public static final String LOGIN_FAIL_TO_LOGIN = "Utilizador ou palavra-passe inválidos";
	public static final String LOGIN_RECOVERY = "Corrija o utiliador ou a palavra-passe e tente de novo";
	public static final String NOT_YET_IMPLEMENTED = "Não implementado até esta iteração";
	public static final String CREATE_INDICATOR_NAME_EXISTS = "Já existe um indicador com este nome";
	public static final String CREATE_INDICATOR_NOME_EXISTS_RECOVERY = "Forneça um nome para o indicador que não exista";
	public static final String CREATE_INDICATOR_INVALID_NAME = "Nome de indicador vazio ou modo não selecionado";
	public static final String CREATE_INDICATOR_INVALID_NAME_RECOVERY = "Forneça um nome correto para o indicador ou selecione um modo";
	public static final String CREATE_INDICATOR_INVALID_EXTENSION = "Extensão vazia";
	public static final String CREATE_INDICATOR_INVALID_EXTENSION_RECOVERY = "Forneça uma extensão válida";
	public static final String CREATE_INDICATOR_INVALID_UNITS = "Unidades não preenchidas";
	public static final String CREATE_INDICATOR_INVALID_UNITS_RECOVERY = "Preencha as unidades";
	public static final String CREATE_INDICATOR_CREATE_ERROR = "Falta preencher informação";
	public static final String CREATE_INDICATOR_NOME_CREATE_RECOVERY = "Preencha a informação em falta";
	public static final String CREATE_INDICATOR_SUCCESS = "Indicador criado com sucesso";
	public static final String CREATE_USER_INVALID_USERNAME = "Nome do utilizador não preenchido";
	public static final String CREATE_USER_INVALID_PASSWORD = "Palavra-passe não preenchida";
	public static final String CREATE_USER_INVALID_PASSWORD_AGAIN = "Palavra-passe de confirmação não preenchida";
	public static final String CREATE_USER_PASSWORD_MISMATCH = "Palavra-passe e a sua confirmação não são idênticas";
	public static final String CREATE_USER_SUCCESS = "Utilizador criado com sucesso";
	public static final String CREATE_USER_FAIL_TO_CREATE = "Não foi possível criar o utilizador";
	public static final String CREATE_USER_FAIL_TO_CREATE_RECOVERY = "Consulte o administrador de sistemas";
	public static final String CREATE_USER_ERROR_VALIDATE_RECOVERY = "Corrija os erros nos campos e tente novamente";
	public static final String USER_TYPE_SUPERVISED = "Orientado";
	public static final String USER_TYPE_SUPERVISOR = "Supervisor";
	public static final String USE_CASE_PRECONDITION_ERROR = "Não há nenhum utilizador autenticado na aplicação";
	public static final String USE_CASE_PRECONDITION_RECOVERY = "Autentique-se na aplicação para a poder utilizar";
	public static final String ADD_OBSERVATIONS_INVALID_DATA = "O campo data ou valor não estão preenchidos corretamente";
	public static final String ADD_OBSERVATIONS_INVALID_DATA_RECOVERY = "Introduza uma data válida e um valor (float) correto";
	public static final String ADD_OBSERVATIONS_NO_DATA = "Não há observações recolhidas";
	public static final String ADD_OBSERVATIONS_NO_DATA_RECOVERY = "Recolha pelo menos uma observação";
	public static final String ADD_OBSERVATIONS_EMPTY_UNIT = "Tem de fornecer uma unidade válida";
	public static final String ADD_OBSERVATIONS_INVALID_EMPTY_UNIT_RECOVERY = "Escolha uma unidade da lista de unidades ou crie uma";
	public static final String ADD_OBSERVATIONS_EMPTY_INDICATOR = "Tem de fornecer um indicador válido";
	public static final String ADD_OBSERVATIONS_INVALID_EMPTY_INDICATOR_RECOVERY = "Escolha um indicador da lista de indicadores ou crie um";
	public static final String ADD_COMPATIBLE_UNIT_INVALID_DATA = "O campo unidade compatível não está preenchido";
	public static final String ADD_COMPATIBLE_UNIT_INVALID_DATA_RECOVERY = "Escolha uma unidade compatível da lista de unidades disponível";
	public static final String CREATE_UNIT_SUCCESS = "Unidade criada com sucesso";
	public static final String CREATE_UNIT_UNDERWAY_ERROR = "Já existe um caso de uso de criar unidade em curso";
	public static final String CREATE_UNIT_UNDERWAY_RECOVERY = "Não pode criar mais do que uma unidade em simultâneo";
	public static final String CREATE_UNIT_INVALID_DESCRIPTION_NICK = "Descrição ou abreviatura da unidade não preenchidas";
	public static final String CREATE_INDICATOR_INVALID_DESCRIPTION_NICK_RECOVERY = "Tem de preencher a descrição e a abreviatura da unidade a criar";
}
